import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from "@react-pdf/renderer";
import type { WorkoutPlan } from "@/types/workout";

// Register custom fonts
Font.register({
  family: "Blogger",
  src: "/fonts/Blogger_Sans.otf",
});

Font.register({
  family: "Motter",
  src: "/fonts/MotterCorpusStd-Regular.woff",
});

// Create styles
const styles = StyleSheet.create({
  page: {
    flexDirection: "column",
    backgroundColor: "#FEFAF6",
    padding: 30,
  },
  header: {
    marginBottom: 30,
    textAlign: "center",
  },
  title: {
    fontFamily: "Motter",
    fontSize: 32,
    color: "#181C14",
    marginBottom: 10,
  },
  subtitle: {
    fontFamily: "Blogger",
    fontSize: 16,
    color: "#D84040",
    marginBottom: 20,
  },
  divider: {
    width: "100%",
    height: 2,
    backgroundColor: "#D84040",
    opacity: 0.1,
    marginVertical: 20,
  },
  workoutCard: {
    marginBottom: 20,
    padding: 20,
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
  },
  workoutHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
  },
  workoutTitle: {
    fontFamily: "Motter",
    fontSize: 24,
    color: "#181C14",
  },
  workoutDay: {
    fontFamily: "Blogger",
    fontSize: 14,
    color: "#D84040",
  },
  exerciseItem: {
    marginBottom: 15,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
    borderBottomStyle: "solid",
  },
  exerciseName: {
    fontFamily: "Blogger",
    fontSize: 16,
    color: "#181C14",
    marginBottom: 5,
  },
  exerciseDetails: {
    flexDirection: "row",
    marginBottom: 8,
  },
  exerciseDetail: {
    fontFamily: "Blogger",
    fontSize: 12,
    color: "#666666",
    marginRight: 15,
  },
  exerciseDescription: {
    fontFamily: "Blogger",
    fontSize: 12,
    color: "#666666",
    lineHeight: 1.4,
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: "center",
  },
  footerText: {
    fontFamily: "Blogger",
    fontSize: 10,
    color: "#999999",
  },
  pageNumber: {
    position: "absolute",
    fontSize: 12,
    bottom: 30,
    left: 0,
    right: 0,
    textAlign: "center",
    color: "#666666",
  },
});

interface WorkoutPlanPDFProps {
  plan: WorkoutPlan;
}

const WorkoutPlanDocument: React.FC<WorkoutPlanPDFProps> = ({ plan }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.title}>{plan.name}</Text>
        <Text style={styles.subtitle}>Your Personalized Fitness Journey</Text>
      </View>

      {/* Plan Details */}
      <View style={styles.workoutCard}>
        <Text style={styles.workoutTitle}>Program Overview</Text>
        <View style={[styles.exerciseDetails, { marginTop: 10 }]}>
          <Text style={styles.exerciseDetail}>
            Duration: {plan.duration} Days
          </Text>
          <Text style={styles.exerciseDetail}>
            Workouts: {plan.workouts.length} Sessions
          </Text>
        </View>
      </View>

      <View style={styles.divider} />

      {/* Workouts */}
      {plan.workouts.map((workout, index) => (
        <View key={index} style={styles.workoutCard}>
          <View style={styles.workoutHeader}>
            <Text style={styles.workoutTitle}>{workout.name}</Text>
            <Text style={styles.workoutDay}>Day {workout.day}</Text>
          </View>

          {workout.exercises.map((exercise, exIndex) => (
            <View key={exIndex} style={styles.exerciseItem}>
              <Text style={styles.exerciseName}>{exercise.name}</Text>
              <View style={styles.exerciseDetails}>
                <Text style={styles.exerciseDetail}>Sets: {exercise.sets}</Text>
                <Text style={styles.exerciseDetail}>Reps: {exercise.reps}</Text>
              </View>
              <Text style={styles.exerciseDescription}>
                {exercise.description}
              </Text>
            </View>
          ))}
        </View>
      ))}

      {/* Footer */}
      <View style={styles.footer}>
        <Text style={styles.footerText}>
          Generated by BodyFlow • Your Personal AI Fitness Trainer
        </Text>
      </View>

      {/* Page Number */}
      <Text
        style={styles.pageNumber}
        render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`}
      />
    </Page>
  </Document>
);

export default WorkoutPlanDocument;
